### ISSUE TITLE
clair-scanner: command not found

### ISSUE THREAD

**Issue by overip** [arminc/clair-local-scan#12]
I followed your steps, which are:

docker run -d --name db arminc/clair-db:2017-03-15
docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.3
clair-scanner nginx:1.11.6-alpine example-nginx.yaml http://MY_LOCAL_IP:6060 MY_LOCAL_IP

but I get the following error:

clair-scanner: command not found

Am I missing anything?

Thanks

**Comment by usr42** [comment]
You have to install [clair-scanner](https://github.com/arminc/clair-scanner) locally to access the clair-local-scan container like this.

Or you could use my [clair-container-scan](https://github.com/usr42/clair-container-scan). Is uses another container to access the clair container.
You don't have to install anything locally. It is just a shell script and everything else is started inside docker containers.
To scan a docker image is as easy as running:
```
./clair-container-scan.sh alpine:3.4
```

Maybe you can give it a try. Feedback, feature requests and bug reports are welcome!

Cheers
