### ISSUE TITLE
Travis job to build db fails

### ISSUE THREAD

**Issue by usr42** [arminc/clair-local-scan#13]
Hi @arminc,

the cron Travis build of the arminc/clair-db docker image is failing since 7 days.
When I have time, I will also have a look into the reasons, but currently I cannot.

Thanks and cheers,
usr42/Balthasar

**Comment by arminc** [comment]
I already had a quick look at it but it seems it can't parse/fetch info from ubuntu cve

**Comment by usr42** [comment]
@arminc https://github.com/arminc/clair-local-scan/pull/14 is fixing this issue. After merging the PR you have to trigger a docker build with version `arminc/clair-local-scan:v2.0.4`.
