### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by shoeper** [arminc/clair-local-scan#16]
Looks like alpine-secdb was moved to https://git.alpinelinux.org/cgit/alpine-secdb and the redirect doesn't work.

**Comment by shoeper** [comment]
Looks like [this PR](https://github.com/coreos/clair/pull/594) fixes the issue. Once it has been merged updating to a more recent version should fix the issue.

**Comment by shoeper** [comment]
And it looks like the initial issue was / is that someone dosed the alpine repository (see https://github.com/coreos/clair/issues/593). There still is ongoing discussion on how to solve the issue.

**Comment by arminc** [comment]
Yeah I am still waiting for the merge. They should move the config to a file, this is already a third time there is an issue with fetching

**Comment by shoeper** [comment]
The PR just changing the URL has now been merged ;)

**Comment by arminc** [comment]
I see but I also need them to release a version (with that a docker container). I could build my own clair but that is not an official "supported" version then.

**Comment by arminc** [comment]
Fixed by #18
