### ISSUE TITLE
unable to start clair-local-scan on my local machine 

### ISSUE THREAD

**Issue by Mryashbhardwaj** [arminc/clair-local-scan#23]
i am able to get the docker psotgres db runing
i.e. 

> docker run -d --name db arminc/clair-db:2017-03-15

but when i try 
> docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6

the container is created but the execution fails with the followig error.
`
{"Event":"pgsql: could not open database: dial tcp 172.17.0.2:5432: getsockopt: no route to host","Level":"fatal","Location":"main.go:96","Time":"2018-10-26 03:42:02.534312"}
`

i also tried stoping the firewall but that didn't help.

**Comment by arminc** [comment]
Maybe the database wasn't started already? If you still have problems please reopen the issue.
