### ISSUE TITLE
do we need the docker host ip

### ISSUE THREAD

**Issue by nicosmaris** [arminc/clair-local-scan#26]
https://github.com/arminc/clair-scanner/issues/63 happens also when starting the container with:

```
docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6
```

Do we need to put the docker host ip?

**Comment by arminc** [comment]
clair-scanner should be able to access the database without the docker ip. If you are still experiencing the problem please reopen the issue and provide more details.
