### ISSUE TITLE
fyi - your db images have risen from ~135mb to now over 2GB since 2019-01-26 

### ISSUE THREAD

**Issue by StefanMadsen** [arminc/clair-local-scan#29]

**Comment by nabadger** [comment]
@arminc any idea what's happening here - this is now at 3GB

https://hub.docker.com/r/arminc/clair-db/tags?page=1

Thanks

**Comment by arminc** [comment]
I think it is because I am reusing the image now instead of using a clean one. I am on holiday, I can have a look next week. If you can create a PR so it uses a fresh DB instead of the one from the previous day I can merge it in. I will see if I can investigate  why it becomes bigger afterwards.
