### ISSUE TITLE
clair-db: add tag latest

### ISSUE THREAD

**Issue by t00f** [arminc/clair-local-scan#3]
Hi @arminc,

Thanks for your useful work. I know it is not the correct repo, but I had no other way to contact you. 

Do you think adding a tag `latest` on the clair-db would be possible ?

Thanks,

**Comment by arminc** [comment]
That already happens https://github.com/arminc/clair-local-scan/blob/19df34858291156de015c6d9d2d3e78e8feb1b45/.travis.yml#L26

**Comment by t00f** [comment]
Weird, I can't pull it from the docker registry:
```
% docker pull  arminc/clair-db       
Using default tag: latest
Pulling repository docker.io/arminc/clair-db
Tag latest not found in repository docker.io/arminc/clair-db
```

**Comment by arminc** [comment]
You are right, I will have a look in to it.

**Comment by arminc** [comment]
It's fixed, it works now.

**Comment by t00f** [comment]
Looks good, thanks @arminc
