### ISSUE TITLE
Tag v2.0.6 on git aligning with Docker Hub

### ISSUE THREAD

**Issue by tnir** [arminc/clair-local-scan#32]
While v2.0.6 can be seen in https://hub.docker.com/r/arminc/clair-local-scan/tags, v2.0.6 tag on Git does not appear.

Can you tag some ref (maybe b263b69e351708ffbc4ede8b7347c69d5f764108) as v2.0.6?

**Comment by arminc** [comment]
done

**Comment by tnir** [comment]
Thanks.
