### ISSUE TITLE
root req in clair-db

### ISSUE THREAD

**Issue by mirekphd** [arminc/clair-local-scan#42]
`arminc/clair-db` has a root requirement, which is not recomennded for prod env (and such containers simply can't be run in Openshift). Why not switch over to safer `bitnami/postgresql`? And why not open-source the db Dockerfile as well (I could not find it)?

To replicate:
`docker run --rm -it --name clair-db --cap-drop=all arminc/clair-db:latest`
`chown: /var/lib/postgresql/clair: Permission denied`

similar problem in the official `postgres`:
`docker run --cap-drop=all postgres`
`chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted`

Without dropping all capabilities (using `--cap-drop=all`) and thus allowing root actions, both of the containers start to work.

In contrast bitnami's Postgres does not require root:
`docker run --cap-drop=all -e POSTGRESQL_PASSWORD=pass123 bitnami/postgresql`
`[..] LOG:  database system is ready to accept connections`

**Comment by arminc** [comment]
@mirekphd I agree. The DB is a clean official postgress image as you can see here: https://github.com/arminc/clair-local-scan/blob/master/.travis.yml 
I think switching wouldn't be that hard. Feel free to try it out and make a PR. The steps on how the DB image is created is all here: https://github.com/arminc/clair-local-scan/blob/master/.travis.yml
