### ISSUE TITLE
db updates broken

### ISSUE THREAD

**Issue by cnbennett3** [arminc/clair-local-scan#55]
The last update to check.sh has converted a warning in the logs into an exit 2.  This prevents the db from being uploaded to DockerHub. 

This means we no longer get security updates. There haven't been any since 10/29/20.

Is this because the warning was preventing the db from being updated correctly? Was it giving false results?

Looking through Travis, I wondered if this a result of upgrading to 2.1.6?  If so, would you consider dropping back to 2.1.5?  It seems like either this should to be fixed (ideally) or downgrading to 2.1.5 undertaken if that will fix it. Going for months without security updates is pretty risky.

That said I understand you support this on a best effort basis.  I don't know all the issues involved but would be willing to try to help out if you like, as long as you're available via email for questions.

**Comment by arminc** [comment]
The idea behind it was: https://github.com/arminc/clair-local-scan/pull/53 but it is a double edged sword.

If we don;t break the build on warning we have incomplete DB which means false sense of protection. If we do break the build we get this situation. I think having a partially updated DB right now is better than having no updates. I (we) should still figure out how to deal with this.

@byteborg fyi

I have removed the exit from the warning for now until we can figure something out, that way the database get's updated again, even if it is partially. (Build is scheduled now)

Eventually the best solution would be to switch to version 4, I just did not have time to look into that for now.
