### ISSUE TITLE
The clair db image is not updated.

### ISSUE THREAD

**Issue by sunminjeon** [arminc/clair-local-scan#63]
Hi,

Looks like the clair db image is not updated anymore.
Last update is shown 2 months ago.

Is there a reason you are not updating?

https://hub.docker.com/r/arminc/clair-db/tags?page=1&ordering=last_updated

**Comment by arminc** [comment]
I did not realize I had to move to Travis com, which doesn't seem to offer
a open source option anymore.
I didn't know that, to make it work again I need to convert the build
script to GitHub actions.

I need to find time for that.

**Comment by roger-lau** [comment]
@arminc Appreciate the hard work maintaining this open source project. While waiting for you to get it running again in a new platform, is there any workaround for us to get the latest database?

**Comment by arminc** [comment]
You can follow the steps here: https://github.com/arminc/clair-local-scan/blob/master/.travis.yml
Or if someone can recreate them for GitHub actions I can test them out and apply the changes.

**Comment by tim-reslv** [comment]
@arminc I try convert travis.yaml to github action and created PR. You may test it.

**Comment by arminc** [comment]
Build is running again.
