### ISSUE TITLE
Tags of arminc/clair-local-scan docker hub image wrong

### ISSUE THREAD

**Issue by usr42** [arminc/clair-local-scan#8]
Thanks for merging my PR to use clair:v2.0.2.

Now that clair:2.0.2 is used as base, also the arminc/clair-local-scan docker hub image should be tagged with v2.0.2.

The v2.0.1 tag in docker hub was overwritten with the v2.0.2 image. This should also be fixed.

**Comment by usr42** [comment]
@arminc Could you please trigger the build with version v2.0.2 and fix the build for v2.0.1?
In addition you could directly merge https://github.com/arminc/clair-local-scan/pull/10 which upgrades to v2.0.3 and add the corresponding build for it.

Could I somehow help you or do you need something else?

**Comment by arminc** [comment]
Thanks for the fixes, will do asap.

**Comment by arminc** [comment]
Tags are set, build 2.0.2 is working fine, 2.0.1 and 2.0.3 has problems fetching data. Does not seem to have anything to do with clair

**Comment by usr42** [comment]
Scanning images is working for me with version 2.0.3.
What data cannot be fetched? The CVE data for filling the db?

**Comment by arminc** [comment]
fixed
